"""
M.i.a or My Intelligent Assistant

Welcome user! Thanks for trying out my project, I hope I made the documentation clear and easy to use
Start with this file, and the rest is pretty much already set up

Dependencies for this project:
    pyowm- used for all of the weather data
        pip install pyowm
    gTTS- used to generate speech
        pip install gTTS
    playsound- used to play the mp3 generated by gtts
        pip install playsound
"""

secrets = {
    "API Key": "Replace this strings text with your API Key, final result should be a string",  # API key for OWM
    "City ID": "Replace this string with your City ID, becoming an int",  # ID of your city, most accurate method
    "Name": "Mia",  # I liked Mia, but it can change to anything
    "Temp System": "fahrenheit",  # Temperature format; Can be Fahrenheit, Celsius, or Kelvin if you're weird
    "Clock Format": "12hr",  # Default is 12hr with AM/PM, can be 24hr without that
}
