"""
M.i.a or My Intelligent Assistant

Welcome user! Thanks for trying out my project, I hope I made the documentation clear and easy to use
Start with this file, and the rest is pretty much already set up

Dependencies for this project:
    pyowm- used for all of the weather data
        pip install pyowm
    gTTS- used to generate speech
        pip install gTTS
    playsound- used to play the mp3 generated by gtts
        pip install playsound

To get values of this config file:
    API Key- Make an account with OpenWeatherMap.org and generate an API key

    City ID- Run cityInfo.py in /SetupScripts, the first value in the first line (the number) is the City ID

    City LatLon- Run cityInfo.py in /SetupScritps, the values labeled lat and lon are the coordinates for your city
        find the one that has an ID that matches up with your city ID and put in those coordinates
"""

secrets = {
    "API Key": "Replace this strings text with your API Key, final result should be a string",  # API key for OWM
    "City ID": "Replace this string with your City ID, becoming an int",  # ID of your city, most accurate method
    "City LatLon": ["Latitude Int", "Longitude Int"],  # Latitude and Longitude of your city for forecast and history
    "Name": "Mia",  # I liked Mia, but it can change to anything
    "Temp System": "fahrenheit",  # Temperature format; Can be Fahrenheit, Celsius, or Kelvin if you're weird
    "Clock Format": "12hr",  # Default is 12hr with AM/PM, can be 24hr without that
}
